micronaut:
  application:
  server:
    name: micronaut-service-template
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

jackson:
  serialization:
    indentOutput: false
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false

endpoints:
  health:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false
